name: Android WAF Build and Artifact (arm64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_arm64:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Configure and build with WAF (ARM64)
      run: |
        ./waf configure --android=arm64-v8a,clang,30
        ./waf build

    - name: Upload ARM64 APK as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: revc-android-arm64-build
        path: |
          build/**/*.apk
