name: Android WAF Build and Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Install NDK
      run: |
        echo "ANDROID_NDK_HOME=${ANDROID_HOME}/ndk-bundle" >> $GITHUB_ENV
        echo "PATH=$PATH:$ANDROID_NDK_HOME" >> $GITHUB_ENV

    - name: Install WAF and Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install waf

    - name: Configure and build with WAF
      run: |
        ./waf configure --android
        ./waf build

    - name: Find and Upload APK as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: revc-android-build
        path: |
          build/**/*.apk
